# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sport on the Move Foundation
email: info@sportonthemove.org
description: >- # this means to ignore newlines until "baseurl:"
  Namibian Sport on the Move Foundation - creating a supportive environment for athletes in Namibia. We believe that creating a supportive environment enables athletes to enter professional sports and compete at the highest level.
baseurl: "" 
repository: anneke/sportsonthemove.github.io
url: "https://www.sportonthemove.org"
instagram_username: sportonthemove

theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

github: [metadata]
